### ISSUE TITLE
Why it print exception stack twice?

### ISSUE THREAD

**Issue by heckad** [aio-libs/aiojobs#146]
Code example
```
import asyncio

import aiojobs


async def f():
    try:
        await asyncio.sleep(2)
    except asyncio.CancelledError:
        print('canceled')
    else:
        print('not canceled')


async def err():
    raise Exception


async def main():
    scheduler = await aiojobs.create_scheduler(close_timeout=None)

    await scheduler.spawn(f())
    await scheduler.spawn(err())

    try:
        await scheduler
    except:
        print('exception occurred, cancel')
        await scheduler.close()
    else:
        print('all good')


if __name__ == '__main__':
    asyncio.run(main())
```
Result
```
exception occurred, cancel
Job processing failed
job: <Job closed coro=<<coroutine object err at 0x000001E5768B1D40>>>
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\test-2uqMFfYk\lib\site-packages\aiojobs\_job.py", line 89, in _close
    await self._task
  File "C:/Users/Asus/Documents/Projects/python/test/sub.py", line 16, in err
    raise Exception
Exception
Job processing failed
job: <Job closed coro=<<coroutine object err at 0x000001E5768B1D40>>>
Traceback (most recent call last):
  File "C:\Users\Asus\.virtualenvs\test-2uqMFfYk\lib\site-packages\aiojobs\_job.py", line 89, in _close
    await self._task
  File "C:/Users/Asus/Documents/Projects/python/test/sub.py", line 16, in err
    raise Exception
Exception
cancelled
```
Why it print stack trace twice?

**Comment by achimnol** [comment]
This may be related to `_explicit` attribute of the `Job` class.
Try force-change it to `False` after spawning.
