### ISSUE TITLE
missing async-timeout requirement

### ISSUE THREAD

**Issue by Korridzy** [aio-libs/aiojobs#246]
Looks like aiojobs have an unsatisfied requirement:
```
homo@darwin:~/git/owlery/hardservice$ mkdir dvenv
homo@darwin:~/git/owlery/hardservice$ virtualenv --python=python3 dvenv
created virtual environment CPython3.8.5.final.0-64 in 295ms
  creator CPython3Posix(dest=/home/homo/git/owlery/hardservice/dvenv, clear=False, global=False)
  seeder FromAppData(download=False, wheel=latest, six=latest, progress=latest, appdirs=latest, lockfile=latest, pip=latest, distro=latest, html5lib=latest, setuptools=latest, CacheControl=latest, ipaddr=latest, certifi=latest, msgpack=latest, retrying=latest, distlib=latest, colorama=latest, pkg_resources=latest, packaging=latest, webencodings=latest, requests=latest, urllib3=latest, contextlib2=latest, pytoml=latest, chardet=latest, idna=latest, pyparsing=latest, pep517=latest, via=copy, app_data_dir=/home/homo/.local/share/virtualenv/seed-app-data/v1.0.1.debian)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
homo@darwin:~/git/owlery/hardservice$ source dvenv/bin/activate
(dvenv) homo@darwin:~/git/owlery/hardservice$ pip install aiojobs
Collecting aiojobs
  Using cached aiojobs-0.3.0-py3-none-any.whl (10.0 kB)
Installing collected packages: aiojobs
Successfully installed aiojobs-0.3.0
(dvenv) homo@darwin:~/git/owlery/hardservice$ python socket_service/socket_server.py 
Traceback (most recent call last):
  File "socket_service/socket_server.py", line 2, in <module>
    import aiojobs
  File "/home/homo/git/owlery/hardservice/dvenv/lib/python3.8/site-packages/aiojobs/__init__.py", line 13, in <module>
    from ._scheduler import Scheduler
  File "/home/homo/git/owlery/hardservice/dvenv/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 3, in <module>
    from ._job import Job
  File "/home/homo/git/owlery/hardservice/dvenv/lib/python3.8/site-packages/aiojobs/_job.py", line 5, in <module>
    import async_timeout
ModuleNotFoundError: No module named 'async_timeout'
```

**Comment by asvetlov** [comment]
Done by #275
