### ISSUE TITLE
"Non-thread-safe operation invoked on an event loop other than the current one" and "RuntimeError: Event loop is closed"

### ISSUE THREAD

**Issue by AIGeneratedUsername** [aio-libs/aiojobs#286]
### Versions:
aiojobs 1.0.0 
Python 3.8
Lubuntu 20.04
pytest-asyncio 0.16.0

Set `PYTHONASYNCIODEBUG=1`

### Tracabeck 

```python
Exception ignored in: <coroutine object Scheduler._wait_failed at 0x7f56ba3fd440>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
    task = await self._failed_tasks.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Scheduler._wait_failed at 0x7f56c8680a40>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
    task = await self._failed_tasks.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Scheduler._wait_failed at 0x7f56b9819cc0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
    task = await self._failed_tasks.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <coroutine object Scheduler._wait_failed at 0x7f56ba3f7ec0>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
    task = await self._failed_tasks.get()
  File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
    await getter
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

```python
=============================== warnings summary ===============================
tests/foobar/spameggspy::test_my_test_name
  /usr/local/lib/python3.8/site-packages/_pytest/unraisableexception.py:78: PytestUnraisableExceptionWarning: Exception ignored in: <coroutine object Scheduler._wait_failed at 0x7f56d1791a40>
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/asyncio/queues.py", line 163, in get
      await getter
  GeneratorExit
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/aiojobs/_scheduler.py", line 129, in _wait_failed
      task = await self._failed_tasks.get()
    File "/usr/local/lib/python3.8/asyncio/queues.py", line 165, in get
      getter.cancel()  # Just in case getter is not done yet.
    File "/usr/local/lib/python3.8/asyncio/base_events.py", line 721, in call_soon
      self._check_thread()
    File "/usr/local/lib/python3.8/asyncio/base_events.py", line 758, in _check_thread
      raise RuntimeError(
  RuntimeError: Non-thread-safe operation invoked on an event loop other than the current one
```

### Reproducible sample
Sorry, I can not give a reproducible sample right now because the project is huge and I do not understand what exactly raises the warning. Any ideas how can I debug this problem by myself? Any suggestions?

**Comment by asvetlov** [comment]
The text is clear: you code makes access to jobs scheduler from multiple threads
