### ISSUE TITLE
The @atomic decorator now work for class grouped handler

### ISSUE THREAD

**Issue by thomaszdxsn** [aio-libs/aiojobs#31]
I watch aiohttp's doc, it teach me use the `aiojobs.atomic` to avoid request cancel.

And I found it not work on class grouped handler, I don't mean class view, just this mean method handler:

```python
class UserRelated(object):
     
    def create_user_handler(self, request):
        ...
```

I investigate the source code, ensure the `@atomic` decorator cause the problem.

## My traceback on class grouped handler

```python
web_protocol.py            310 ERROR    Error handling request
Traceback (most recent call last):
  File ".../lib/python3.6/site-packages/aiohttp/web_protocol.py", line 381, in start
    resp = await self._request_handler(request)
  File ".../lib/python3.6/site-packages/aiohttp/web_app.py", line 322, in _handle
    resp = await handler(request)
TypeError: wrapper() takes 1 positional argument but 2 were given

```

**Comment by asvetlov** [comment]
Sorry, I don't see how to fix it in a generic way.
A custom decorator for instance method can be created easily though.
Or we can support `@atomic(method=True)` construction.

**Comment by thomaszdxsn** [comment]
It is a good idea, but for support back-compat, `@atomic` must have both call usage and non-call usage.

or just use `inspect.ismethod()`?

```python
def atomic(coro):
    @wraps(coro)
    async def wrapper(*args):
        if inspect.ismethod(coro):
            assert len(args) == 2
            _instance, request = args
        else:
            assert len(args) == 1
            request = args[0]
                if isinstance(request, View):
                    # Class Based View decorated.
                    request = request.request

        job = await spawn(request, coro(request))
        return await job.wait()
    return wrapper
```

but the code look is ugly, and more expensive.

**Comment by asvetlov** [comment]
> It is a good idea, but for support back-compat, @atomic must have both call usage and non-call usage.

Yes.

> but the code look is ugly, and more expensive.

That's why I did not support classes from very beginning (and still not sure what way is better now).

**Comment by thomaszdxsn** [comment]
Ok.

We should postpone this issue if not have better idea. 

But maybe we can add some doc for illustrate?
